# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'object_detection.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again. Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.image_label = QtWidgets.QLabel(self.centralwidget)
        self.image_label.setMinimumSize(QtCore.QSize(640, 480))
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label.setObjectName("image_label")
        self.image_label.setStyleSheet("background-color: lightgray; border: 1px solid black;")
        self.horizontalLayout.addWidget(self.image_label)
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setMinimumSize(QtCore.QSize(640, 480))
        self.result_label.setAlignment(QtCore.Qt.AlignCenter)
        self.result_label.setObjectName("result_label")
        self.result_label.setStyleSheet("background-color: lightgray; border: 1px solid black;")
        self.horizontalLayout.addWidget(self.result_label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        # self.upload_button = QtWidgets.QPushButton(self.centralwidget)  # Commented out to remove the button
        # self.upload_button.setObjectName("upload_button")  # Commented out to remove the button
        # self.horizontalLayout_2.addWidget(self.upload_button)  # Commented out to remove the button
        self.start_webcam_button = QtWidgets.QPushButton(self.centralwidget)
        self.start_webcam_button.setObjectName("start_webcam_button")
        self.horizontalLayout_2.addWidget(self.start_webcam_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Webcam Object Detection"))
        self.image_label.setText(_translate("MainWindow", "No Image"))
        self.result_label.setText(_translate("MainWindow", "No Image"))
        # self.upload_button.setText(_translate("MainWindow", "Upload Image"))  # Commented out to remove the button
        self.start_webcam_button.setText(_translate("MainWindow", "Start Webcam"))


